// Smoke tests for the Node.js native addon produced by `napi build`
// in `crates/napi/`. Loads the platform-specific `.node` artefact
// via the generated `index.js` loader, exercises every exported
// function at least once, and asserts the JSON-envelope error
// contract documented in `crates/napi/src/bindings.rs`.
//
// Runs under `node --test test/`. Exits non-zero on any assertion
// failure so CI can fail fast.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, copyFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, resolve as resolvePath, join as joinPath } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const requireCJS = createRequire(import.meta.url);
const core = requireCJS(resolvePath(here, '..', 'index.js'));

// ----------------------------------------------------------------
// Fixture helpers
// ----------------------------------------------------------------

// Build a real ``.pack`` file on disk by shelling out to the
// ``pack-build`` Rust binary over a small synthetic JSONL fixture.
// Using a real pack (rather than a hand-rolled byte buffer) is the
// only way to exercise the full open + verify + extract + search
// path the napi bridge takes in production.
//
// pack-build is invoked exactly ONCE per test process via the
// memoised ``sharedPack()`` helper below; ``buildTestPack()`` then
// copies the resulting ``.pack`` bytes into a fresh tempdir per
// caller. That preserves the per-test workdir cleanup contract
// (cleanup() rms the workdir) while removing the ~10x cargo
// subprocess overhead the original implementation incurred. The
// pack contents are identical across every test in this file, so
// sharing the build is safe — tests that need distinct *handles*
// against distinct pack *files* (e.g. ``multiple open packs have
// distinct handles``) still get distinct files via the copy.

let _sharedPack = null;
function sharedPack() {
  if (_sharedPack !== null) return _sharedPack;

  const buildDir = mkdtempSync(joinPath(tmpdir(), 'pack-napi-shared-'));
  const packsRoot = joinPath(buildDir, 'packs');
  // pack-build's ``ingest_jsonl_files`` walks only ``metadata/`` and
  // ``chunks/`` — the governance log is auto-generated by
  // ``ingest_episode`` / ``ingest_chunk`` during ingest, so we
  // intentionally do NOT create a ``governance/`` directory or write
  // a pre-baked rights_log.jsonl. The Python pipeline writes one as
  // an audit trail of what the Python side ingested, but the Rust
  // ingest path doesn't consume it.
  for (const sub of ['metadata', 'chunks']) {
    execFileSync('mkdir', ['-p', joinPath(packsRoot, sub)]);
  }

  const episode = {
    episode_id: 'smoketest_flagship_widgets',
    publisher: 'smoketest',
    series: 'flagship',
    title: 'Widgets',
    host: ['Host One'],
    guest: [],
    publication_date: '2025-01-01',
    country_region: ['US'],
    industry_tags: ['manufacturing'],
    function_tags: ['operations'],
    business_model_tags: ['B2B'],
    source_type: 'podcast_transcript_html',
    language: 'en',
    primary_url: 'https://example.com/ep/1',
    asset_urls: [],
    rights_code: 'free_access_copyrighted',
    rights_summary: 'Test fixture only.',
    credibility_notes: '',
    summary: 'A test episode about widget manufacturing.',
    chunking_policy: { target_tokens: 700, overlap_tokens: 120 },
  };
  const chunk = {
    chunk_id: 'smoketest_flagship_widgets#0001',
    episode_id: episode.episode_id,
    token_count: 16,
    section_heading: 'Manufacturing',
    chunk_text:
      'HOST: Widgets are manufactured in batches of one hundred. The factory runs three shifts.',
    citation_anchor: `${episode.primary_url}#section-1`,
  };
  writeFileSync(
    joinPath(packsRoot, 'metadata', 'smoketest.jsonl'),
    JSON.stringify(episode) + '\n',
  );
  writeFileSync(
    joinPath(packsRoot, 'chunks', 'smoketest.jsonl'),
    JSON.stringify(chunk) + '\n',
  );

  const packPath = joinPath(buildDir, 'smoke.pack');
  // Resolve the workspace root by walking up from this test file
  // (`crates/napi/test/`).
  const workspaceRoot = resolvePath(here, '..', '..', '..');
  execFileSync(
    'cargo',
    [
      'run',
      '--manifest-path',
      joinPath(workspaceRoot, 'Cargo.toml'),
      '--quiet',
      '--bin',
      'pack-build',
      '--',
      '--packs-root',
      packsRoot,
      '--output',
      packPath,
    ],
    { stdio: 'inherit' },
  );

  _sharedPack = { buildDir, packPath };
  return _sharedPack;
}

function buildTestPack() {
  const { packPath: sharedPackPath } = sharedPack();
  const workdir = mkdtempSync(joinPath(tmpdir(), 'pack-napi-smoke-'));
  const packPath = joinPath(workdir, 'smoke.pack');
  // ``copyFileSync`` is enough — every test treats the pack as
  // read-only at the FS level (the napi bridge decompresses into
  // its own tempdir before opening SQLite). A simple copy is
  // ~10μs vs. ~500ms for a fresh cargo invocation.
  copyFileSync(sharedPackPath, packPath);
  return { workdir, packPath };
}

function cleanup(workdir) {
  try {
    rmSync(workdir, { recursive: true, force: true });
  } catch (_err) {
    // Best-effort cleanup; tempdirs are eventually reaped by the OS.
  }
}

// ----------------------------------------------------------------
// Surface assertions
// ----------------------------------------------------------------

test('exports the documented surface', () => {
  assert.equal(typeof core.openPack, 'function');
  assert.equal(typeof core.search, 'function');
  assert.equal(typeof core.closePack, 'function');
});

// ----------------------------------------------------------------
// Error envelope contract
// ----------------------------------------------------------------

test('openPack on missing file raises Io envelope', () => {
  try {
    core.openPack('/nonexistent/path/to/missing.pack');
    assert.fail('expected openPack to throw on missing file');
  } catch (err) {
    const parsed = JSON.parse(err.message);
    assert.equal(parsed.kind, 'Io');
    assert.ok(parsed.message.length > 0);
  }
});

test('openPack on truncated file raises TruncatedPack envelope', () => {
  const workdir = mkdtempSync(joinPath(tmpdir(), 'pack-napi-truncated-'));
  const path = joinPath(workdir, 'truncated.pack');
  // 4 bytes — strictly less than MIN_HEADER_BYTES (22). PackReader
  // returns TruncatedPack.
  writeFileSync(path, Buffer.from('SNMD'));
  try {
    core.openPack(path);
    assert.fail('expected openPack to throw on truncated file');
  } catch (err) {
    const parsed = JSON.parse(err.message);
    assert.equal(parsed.kind, 'TruncatedPack');
  } finally {
    cleanup(workdir);
  }
});

test('search on zero (sentinel) handle raises InvalidArgument', () => {
  try {
    core.search(0n, {});
    assert.fail('expected search(0n) to throw');
  } catch (err) {
    const parsed = JSON.parse(err.message);
    assert.equal(parsed.kind, 'InvalidArgument');
  }
});

test('closePack on unknown handle returns false (not throws)', () => {
  // ``999_999n`` was never minted in this process. Idempotent
  // close must return false, not raise.
  const removed = core.closePack(999_999n);
  assert.equal(removed, false);
});

test('closePack on zero (sentinel) handle returns false', () => {
  const removed = core.closePack(0n);
  assert.equal(removed, false);
});

// ----------------------------------------------------------------
// Round-trip: open a real pack, run a search, close
// ----------------------------------------------------------------

test('open → search → close round-trips against a real .pack', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    assert.equal(typeof handle, 'bigint');
    assert.notEqual(handle, 0n);

    const hits = core.search(handle, { text: 'widgets', limit: 5 });
    assert.ok(Array.isArray(hits));
    assert.equal(hits.length, 1);
    const hit = hits[0];
    // Response keys are camelCase to match the JS surface.
    assert.equal(hit.chunkId, 'smoketest_flagship_widgets#0001');
    assert.equal(hit.episodeId, 'smoketest_flagship_widgets');
    assert.ok(typeof hit.rankScore === 'number');
    // BM25 should fire because the text query matches.
    assert.ok(hit.bm25Score !== null && hit.bm25Score !== undefined);
    assert.equal(hit.tagMatch, false);
    assert.ok(typeof hit.createdAt === 'number');
    assert.equal(hit.citationAnchor, 'https://example.com/ep/1#section-1');
    assert.equal(hit.sectionHeading, 'Manufacturing');
    // Verify no snake_case sneak-through.
    assert.equal(hit.chunk_id, undefined);
    assert.equal(hit.rank_score, undefined);

    const closed = core.closePack(handle);
    assert.equal(closed, true);

    // After close, a follow-up search must surface
    // InvalidArgument (the handle is no longer in the registry).
    try {
      core.search(handle, { text: 'widgets' });
      assert.fail('expected post-close search to throw');
    } catch (err) {
      const parsed = JSON.parse(err.message);
      assert.equal(parsed.kind, 'InvalidArgument');
    }

    // Idempotent double-close returns false.
    assert.equal(core.closePack(handle), false);
  } finally {
    cleanup(workdir);
  }
});

test('tag-only search returns the chunk via structured match', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    const hits = core.search(handle, {
      text: '',
      tags: { industry: ['manufacturing'] },
      limit: 5,
    });
    assert.equal(hits.length, 1);
    assert.equal(hits[0].chunkId, 'smoketest_flagship_widgets#0001');
    // Tag-only queries always set ``tagMatch = true``.
    assert.equal(hits[0].tagMatch, true);
    core.closePack(handle);
  } finally {
    cleanup(workdir);
  }
});

test('search returns empty array when nothing matches', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    const hits = core.search(handle, { text: 'no_such_token_anywhere' });
    assert.deepEqual(hits, []);
    core.closePack(handle);
  } finally {
    cleanup(workdir);
  }
});

test('multiple open packs have distinct handles', () => {
  const a = buildTestPack();
  const b = buildTestPack();
  try {
    const ha = core.openPack(a.packPath);
    const hb = core.openPack(b.packPath);
    assert.notEqual(ha, hb);
    core.closePack(ha);
    core.closePack(hb);
  } finally {
    cleanup(a.workdir);
    cleanup(b.workdir);
  }
});

test('camelCase businessModel and evidenceType filters are honored', () => {
  // Regression for the silent-loss bug: the JS surface accepts
  // ``businessModel`` / ``evidenceType`` (camelCase, matching the
  // rest of the request body). Sending those keys must filter the
  // result set, not silently fall through to defaults.
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);

    // Hit on businessModel — the fixture is tagged ``B2B``.
    let hits = core.search(handle, {
      text: '',
      tags: { businessModel: ['B2B'] },
      limit: 5,
    });
    assert.equal(hits.length, 1);
    assert.equal(hits[0].chunkId, 'smoketest_flagship_widgets#0001');

    // Miss on businessModel — a tag the fixture does not carry.
    hits = core.search(handle, {
      text: '',
      tags: { businessModel: ['nonprofit'] },
      limit: 5,
    });
    assert.deepEqual(hits, []);

    // Hit on evidenceType — fixture's ``source_type`` is
    // ``podcast_transcript_html``.
    hits = core.search(handle, {
      text: '',
      tags: { evidenceType: ['podcast_transcript_html'] },
      limit: 5,
    });
    assert.equal(hits.length, 1);
    assert.equal(hits[0].chunkId, 'smoketest_flagship_widgets#0001');

    // Miss on evidenceType.
    hits = core.search(handle, {
      text: '',
      tags: { evidenceType: ['whitepaper'] },
      limit: 5,
    });
    assert.deepEqual(hits, []);

    core.closePack(handle);
  } finally {
    cleanup(workdir);
  }
});

test('snake_case businessModel key on the JS surface is treated as unknown', () => {
  // Defense in depth: if a caller mistakenly sends ``business_model``
  // (snake_case), the camelCase-only typed deserialiser must
  // either ignore the unknown key or raise. Either way, the
  // documented camelCase contract is preserved — there's no
  // silent fallback that admits the snake_case spelling.
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    const hits = core.search(handle, {
      text: '',
      tags: { business_model: ['B2B'] },
      limit: 5,
    });
    // ``business_model`` (snake_case) is unknown to JsTagFilter,
    // so the filter collapses to all-empty, which means no lane
    // is active (no text, no active tags, no embedding). The
    // search correctly returns 0 hits. If the snake_case key
    // WERE honoured, ``businessModel: ['B2B']`` would activate
    // the tag-only lane and match the fixture's episode, yielding
    // 1 hit. Asserting 0 proves the snake_case key was dropped.
    assert.deepEqual(hits, []);
    core.closePack(handle);
  } finally {
    cleanup(workdir);
  }
});

test('local-only scope accepted (kebab-case)', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    const hits = core.search(handle, {
      text: 'widgets',
      scope: 'local-only',
      limit: 5,
    });
    assert.equal(hits.length, 1);
    assert.equal(hits[0].chunkId, 'smoketest_flagship_widgets#0001');
    core.closePack(handle);
  } finally {
    cleanup(workdir);
  }
});

test('unknown scope spelling raises InvalidArgument', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    try {
      // ``LocalOnly`` (PascalCase) is NOT the wire format —
      // the JS surface expects kebab-case (``local-only``).
      core.search(handle, { text: 'widgets', scope: 'LocalOnly' });
      assert.fail('expected PascalCase scope to throw');
    } catch (err) {
      const parsed = JSON.parse(err.message);
      assert.equal(parsed.kind, 'InvalidArgument');
    } finally {
      core.closePack(handle);
    }
  } finally {
    cleanup(workdir);
  }
});

test('malformed search request raises InvalidArgument', () => {
  const { workdir, packPath } = buildTestPack();
  try {
    const handle = core.openPack(packPath);
    try {
      // ``tags`` as a string instead of an object: cannot
      // deserialise into the typed QueryRequest.
      core.search(handle, { tags: 'industry' });
      assert.fail('expected malformed request to throw');
    } catch (err) {
      const parsed = JSON.parse(err.message);
      assert.equal(parsed.kind, 'InvalidArgument');
    } finally {
      core.closePack(handle);
    }
  } finally {
    cleanup(workdir);
  }
});
